<!DOCTYPE html>
<html>
<head>
	<?php //require_once '../resources/Views/templates/head.phtml'; ?>
	
	<title><?= $this->structure->title ?></title>

	<?php if (@$this->structure->links): ?>
	<?php foreach ($this->structure->links as $link): ?>
		<link src="<?=$this->getDir()?>/resources/css/<?=$link?>.css">		
	<?php endforeach ?>
	<?php endif ?>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
	<?php //require_once '../templates/scripts.phtml'; ?>

	<?php if (@$this->structure->scripts): ?>
	<?php foreach ($this->structure->scripts as $script): ?>
		<script src="<?=$this->getDir()?>/resources/js/<?=$script?>.js"></script>				
	<?php endforeach ?>
	<?php endif ?>
</head>
<body>
	<?= $this->content() ?>
</body>
</html>