<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- Tell the browser to be responsive to screen width -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Favicon icon -->
	<link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png">
	<title><?= $this->structure->title ?></title>
	<!-- Bootstrap Core CSS -->
	<link href="../resources/css/lib/bootstrap/bootstrap.min.css" rel="stylesheet">
	<!-- Custom CSS -->
	<link href="../resources/css/lib/owl.theme.default.min.css" rel="stylesheet" />
	<link href="../resources/css/helper.css" rel="stylesheet">
	<link href="../resources/css/style.css" rel="stylesheet">
	<!-- Toastr - mensagens -->
	<link href="../resources/css/lib/toastr/toastr.min.css" rel="stylesheet">
	
	<?php if (@$this->structure->links): ?>
	<?php foreach ($this->structure->links as $link): ?>
		<link src="<?=$this->getDir()?>/resources/css/<?=$link?>.css">		
	<?php endforeach ?>
	<?php endif ?>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
	<!-- All Jquery -->
	<script src="js/lib/jquery/jquery.min.js"></script>
	<!-- Bootstrap tether Core JavaScript -->
	<script src="js/lib/bootstrap/js/popper.min.js"></script>
	<script src="js/lib/bootstrap/js/bootstrap.min.js"></script>
	<!-- slimscrollbar scrollbar JavaScript -->
	<script src="js/jquery.slimscroll.js"></script>
	<!-- Icons -->
	<script src="https://kit.fontawesome.com/679351656b.js" crossorigin="anonymous"></script>
	<!--Menu sidebar -->
	<script src="js/sidebarmenu.js"></script>
	<!--stickey kit -->
	<script src="js/lib/sticky-kit-master/dist/sticky-kit.min.js"></script>
	<!-- Toastr - mensagens -->
	<script src="js/lib/toastr/toastr.min.js"></script>
	<script src="js/lib/toastr/toastr.init.js"></script>
	<!--Custom JavaScript -->
	<script src="js/scripts.js"></script>

	<?php if (@$this->structure->scripts): ?>
	<?php foreach ($this->structure->scripts as $script): ?>
		<script src="<?=$this->getDir()?>/resources/js/<?=$script?>.js"></script>				
	<?php endforeach ?>
	<?php endif ?>
</head>
<body>
	<?= $this->content() ?>
</body>
</html>