<!DOCTYPE html>
<html>
<head>
	<?php require_once 'resources/Views/templates/head.phtml'; ?>

	<title><?= $this->structure->title ?></title>
	
	<?php if (@$this->structure->links): ?>
	<?php foreach ($this->structure->links as $link): ?>
		<link src="<?=$this->getDir()?>/resources/css/<?=$link?>.css">		
	<?php endforeach ?>
	<?php endif ?>



</head>
<body>
	<div id="main-wrapper">
		<?php require_once 'resources/Views/templates/header.phtml'; ?>
		<?php require_once 'resources/Views/templates/menu.phtml'; ?>
		
		<div class="page-wrapper">
			<?= $this->content() ?>
		</div>
	
	</div>

	<?php require_once 'resources/Views/templates/scripts.phtml'; ?>

	<?php if (@$this->structure->scripts): ?>
	<?php foreach ($this->structure->scripts as $script): ?>
		<script src="<?=$this->getDir()?>/resources/js/<?=$script?>.js"></script>				
	<?php endforeach ?>
	<?php endif ?>
</body>
</html>