<!-- Bootstrap core JavaScript-->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="resources/js/scripts.js"></script>

<!-- Page level plugins -->
<!-- <script src="vendor/chart.js/Chart.min.js"></script> -->

<script src="vendor/toastr/toastr.min.js"></script>
<script type="text/javascript">
	toastr.options.showMethod = 'slideDown';
	toastr.success('Have Fun')
</script>

<!-- Page level custom scripts -->
<!-- <script src="resources/js/demo/chart-area-demo.js"></script> -->
<!-- <script src="resources/js/demo/chart-pie-demo.js"></script> -->