<!DOCTYPE html>
<html>
<head>
	<!-- https://startbootstrap.com/previews/sb-admin-2#google_vignette -->
	<title><?= $this->structure->title ?></title>
	<?php 
		require_once 'resources/Layouts/includes/head.phtml';
		if(@$this->structure->links){
			foreach ($this->structure->links as $link){
				echo "<link src=\"".$this->getDir()."/resources/css/$link.css\">";
			}
		}
		if(@$this->structure->internalStyles){
			echo "<link src=\"".$this->view->path.$this->structure->internalStyles.".css\">";
		}
	?>

</head>
<body>
	<!-- Page Wrapper -->
    <div id="wrapper">

		<?php require_once 'resources/Layouts/includes/sidebar.phtml'; ?>

		<!-- Content Wrapper -->
	    <div id="content-wrapper" class="d-flex flex-column">

	        <!-- Main Content -->
	        <div id="content">

				<?php require_once 'resources/Layouts/includes/header.phtml'; ?>
			
				<div class="container-fluid">
					<?= $this->content() ?>
				</div>
			</div>
		</div>

	</div>
	<?php 
		require_once 'resources/Layouts/includes/scripts.phtml';
		if(@$this->structure->scripts){
			foreach ($this->structure->scripts as $script){
				echo "<script src=\"".$this->getDir()."/resources/js/$script.js\"></script>";
			}
		}

		if($this->structure->internalScripts){
			echo "<script src=\"".$this->view->path.$this->structure->internalScripts.".js\"></script>";
		}
	?>

</body>
</html>