<!-- Main wrapper  -->
<div class="error-page" id="wrapper">
    <div class="error-box">
        <div class="error-body text-center">
            <h1>404</h1>
            <h3 class="text-uppercase">Página não encontrada </h3>
            <p class="text-muted m-t-30 m-b-30">Volte depois de algum tempo</p>
            <a class="btn btn-info btn-rounded waves-effect waves-light m-b-40" href="<?=$this->getUrl()?>">Voltar a home</a> 
        </div>
    </div>
</div>
<!-- End Wrapper -->
