<!-- Bread crumb -->
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-primary"><?=$page->name?></h3> </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= $BASE_URL . $page->url_path?>"><?=$page->name?></a></li>
            <li class="breadcrumb-item active"><?=$page->group?></li>
        </ol>
    </div>
</div>
<!-- End Bread crumb -->
