<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png">
<!-- Bootstrap Core CSS -->
<link href="../resources/css/lib/bootstrap/bootstrap.min.css" rel="stylesheet">

<!-- Custom CSS -->
<link href="../resources/css/lib/owl.theme.default.min.css" rel="stylesheet" />
<link href="../resources/css/helper.css" rel="stylesheet">
<link href="../resources/css/style.css" rel="stylesheet">

<!-- Toastr - mensagens -->
<link href="../resources/css/lib/toastr/toastr.min.css" rel="stylesheet">
