<!-- All Jquery -->
<script src="js/lib/jquery/jquery.min.js"></script>

<!-- Bootstrap tether Core JavaScript -->
<script src="js/lib/bootstrap/js/popper.min.js"></script>
<script src="js/lib/bootstrap/js/bootstrap.min.js"></script>

<!-- slimscrollbar scrollbar JavaScript -->
<script src="js/jquery.slimscroll.js"></script>

<!-- Icons -->
<script src="https://kit.fontawesome.com/679351656b.js" crossorigin="anonymous"></script>

<!--Menu sidebar -->
<script src="js/sidebarmenu.js"></script>

<!--stickey kit -->
<script src="js/lib/sticky-kit-master/dist/sticky-kit.min.js"></script>

<!-- Toastr - mensagens -->
<script src="js/lib/toastr/toastr.min.js"></script>
<script src="js/lib/toastr/toastr.init.js"></script>

<!--Custom JavaScript -->
<script src="js/scripts.js"></script>