<!-- All Jquery -->
<script src="vendor/components/jquery/jquery.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- slimscrollbar scrollbar JavaScript -->
<script src="js/jquery.slimscroll.js"></script>

<!-- Icons -->
<script src="https://kit.fontawesome.com/679351656b.js" crossorigin="anonymous"></script>

<!--Menu sidebar -->
<script src="js/sidebarmenu.js"></script>

<!--stickey kit -->
<script src="resources/js/lib/sticky-kit-master/dist/sticky-kit.min.js"></script>

<!--Custom JavaScript -->
<script src="resources/js/scripts.js"></script>